package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("рфс")
    void generatedTest() {
        step("1. http://rfs-stage.gost-group.com/login", () -> {
            step("// todo: just add selenium action");
        });

        step("2.Авторизоваться под sys/123456", () -> {
            step("// todo: just add selenium action");
        });

        step("3. Перейти в раздел \"Управление\".", () -> {
            step("// todo: just add selenium action");
        });

        step("4. В блоке \"Участники\" нажать кнопку \"Создать профиль\"", () -> {
            step("// todo: just add selenium action");
        });

        step("5. \"Заполнить следующие поля:", () -> {
            step("// todo: just add selenium action");
        });

        step("6. \"\"Фамилия\"\",", () -> {
            step("// todo: just add selenium action");
        });

        step("7.\"\"Имя\"\",", () -> {
            step("// todo: just add selenium action");
        });

        step("8.\"\"Отчество\"\",", () -> {
            step("// todo: just add selenium action");
        });

        step("9.\"\"Пол\"\",", () -> {
            step("// todo: just add selenium action");
        });

        step("10.\"\"Дата рождения\"\",", () -> {
            step("// todo: just add selenium action");
        });

        step("11.\"\"Гражданство\"\",", () -> {
            step("// todo: just add selenium action");
        });

        step("12. \"\"Страна рождения\"\",", () -> {
            step("// todo: just add selenium action");
        });

        step("13. \"\"Примечание\"\".\"", () -> {
            step("// todo: just add selenium action");
        });

        step("14.Добавить файл в блок \"Заявление на регистрацию\".", () -> {
            step("// todo: just add selenium action");
        });

        step("15.Нажать кнопку \"Выберите\"", () -> {
            step("// todo: just add selenium action");
        });

        step("16.Выбрать нужный файл двойным нажатием", () -> {
            step("// todo: just add selenium action");
        });

        step("17.Курсором выбрать на фото область отображения в профиле", () -> {
            step("// todo: just add selenium action");
        });

        step("18. Нажать кнопку \"Применить\"", () -> {
            step("// todo: just add selenium action");
        });

        step("19. Нажать \"Сохранить\".", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'http://rfs-stage.gost-group.com/login'", () ->
            open("http://rfs-stage.gost-group.com/login"));

        step("Page title should have text 'РФС. Цифровая платформа'", () -> {
            String expectedTitle = "РФС. Цифровая платформа";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'http://rfs-stage.gost-group.com/login'", () ->
            open("http://rfs-stage.gost-group.com/login"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}